[package]
name = "tachikoma-common-config"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Configuration types for Tachikoma"

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_yaml = { workspace = true }